[build]
  # All commands run from repo root
  base = "frontend"
  publish = "build"
  # Disable CI variable to prevent CRA from treating warnings as errors
  command = "CI=false npm run build"

[redirects]
  # Single Page App routing fallback handled via public/_redirects file
