[build]
  # All commands run from repo root
  base = "frontend"
  publish = "build"
  # Disable CI variable to prevent CRA from treating warnings as errors
  command = "CI=false npm run build"

[redirects]
  # Single Page App routing fallback handled via public/_redirects file

[context.production.environment]
  # Production environment variables
  REACT_APP_GA_MEASUREMENT_ID = "G-XXXXXXXXXX"
